# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      network: host
    image: pack_ai_test:latest
    container_name: pack_ai_test
    restart: always
    network_mode: host
#    ports:
#      - "8001:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
